### ISSUE TITLE
Import/Export form settings

### ISSUE THREAD

**Issue by BryceBubbles** [am-impact/amforms#143]
First up, we use amforms on all our Craft sites, so thanks for the awesome plugin 👍 )

This is really a question/request.

It would be great to be able to Import/Export form and field settings, so that common setups could be moved between sites and environments.

There's the great Import/Export plugins for general content, and there's the likes of The Architect plugin for handling Fields and Sections. But currently I'm having to recreate forms across different environments and sites, which is more time consuming than I'd like (note we haven't worked out a satisfactory database management solution for Craft yet). So...

- How do you generally handle this sort of thing? 
- Is it something you might build in to the plugin?
- Or is there a way to get The Architect plugin (or other) to handle exporting forms and form fields?

Thanks for any help you can offer.

**Comment by hubertprein** [comment]
I understand that this is a pain. We create forms every day and yes, it's repetitive work that could use some simple tool in order to get things done. We might add something in the plugin later on, or support The Architect plugin, but for now, we have to keep things as they are for now until we have more spare time on our hands.
