### ISSUE TITLE
Limiting 1 submission for a form per user

### ISSUE THREAD

**Issue by prash** [am-impact/amforms#148]
Is this currently possible? I did not see anything in the documentation nor the settings for this.  If possible I'd like this feature to be implemented.

**Comment by hubertprein** [comment]
This is currently not possible, but you can simply create something like that. Simply use the event `onBeforeSaveSubmission` in your own (new) plugin and keep a record of which user has already filled out the form. If the user already did (because the record exists) simply make sure the `performAction` of the Event is set to **false**, and the submission won't be saved.

As you are the only one that has requested it so far, and we have no clients ourselves that require such a feature, we won't implement it in the plugin ourselves anytime soon I'm afraid.
