### ISSUE TITLE
Form template str replace triggers error

### ISSUE THREAD

**Issue by bertoost** [am-impact/amforms#77]
For example, use this template setup:

```
Form: elements/forms/form
Tab: elements/forms/tab
Field: elements/forms/field
```

Because of the str_replace() in **services/AmFormsServices.php** on line 86

```
$templatePath = craft()->path->getSiteTemplatesPath() . str_replace(DIRECTORY_SEPARATOR . $defaultTemplate, '', implode(DIRECTORY_SEPARATOR, $pathParts));
```

The  "/form" is replaced bij nothing. The end result of the Form Template is: **elementss** and that's not the right path.

## Solution
As I look at the code, this should be way simpler.
For example; check if it is a directory; eq. PHP's is_dir() (or use a helper (dont know if it exists)).
When it's a directory, concat the default template name.
When not, and it's not ending on a slash, assume it's a file and walk through the extensions then.

**Comment by hubertprein** [comment]
Hmm never really ran into this problem as we don't specify the last part, like in your case. This is because it will try to find the default template, which in the first case is *form*. The way it's build right now could probably be simpler indeed, but the whole point here is trying to get the path and the template name itself. So the solution you've given, only solves a part of the problem because I still need to get the template name if the default name (e.g. form) is overwritten.

In your case you could do:

Form: elements/forms
Tab: elements/forms
Field: elements/forms

**Comment by bertoost** [comment]
Isn't easier to check if it is a file, then use it, otherwise check if it is a directory then use the defaults from that directory? :-)

**Comment by hubertprein** [comment]
Still, I need the path and the file itself separated from each other :)

It's updated in the dev branch at the moment, see: https://github.com/am-impact/amforms/commit/fa7cd2ce050577b11805d15441afc08d663cea2f

**Comment by bertoost** [comment]
Cool! Will test it a.s.a.p. Thanks!

**Comment by bertoost** [comment]
This works. Even database updates are processed perfectly. Great work!
