### ISSUE TITLE
Can no longer access Globals from Email template

### ISSUE THREAD

**Issue by robzor** [am-impact/amforms#82]
Hi there,

In the old version of A&M Forms, I was using this code in my notification template:

```
{% set siteEmails = siteEmails.siteEmailBody.first() %}
{% if siteEmails.emailRequestASample is defined %}

	{{ siteEmails.siteEmailBody.first().emailRequestASample }}

{% endif %}
```

which references a Global field with some e-mail copy (so the client can write their own copy). This worked until I upgraded to 1.4.3 and now silently fails to send the email notification, and causes the 'single item export' (from the submissions view) to show a Failed Task.

Any ideas how I can fix this?

Thanks,

Rob

**Comment by hubertprein** [comment]
Nothing changed, you can still access your global fields just fine.

On the other hand, you're code isn't really valid.

1. You're defining a variable **siteEmails** that is the **same** name as your **global set name**. I'd suggest you'd never do that as that makes a super mess of your code and creates unintended behaviour.
2. You're requesting an element of a field that might not be filled out in the CP, which could basically perform a `first` function request on a `null` variable. That'll result in an error. Which is probably what's happening in your situation at the moment.
3. The `if` statement, that checks if a field is defined in the global, will **never** work. That's because **all** the Craft fields that you've created, are available when you request information from the global. That's because it has a field layout, and basically a field layout has access to all created Craft fields. So never check if it's defined.. rather check if it's filled out or not with the `length` filter. E.g.: `{% if siteEmails.emailRequestASample|length %}`

**Comment by robzor** [comment]
Hi Hubert,

Thanks for replying. You're right, I shouldn't have set a field to be named as the actual global set, my bad! The field itself is actually a SuperTable which has multiple children, but a single row, hence the first().

I'll do some more testing, but as I said previously, this did work (For whatever reason) before, and in the meantime I've just downgraded to my previous version, (1.3.4). Weird!
